// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Jub_Filecoin.proto

package com.jubiter.sdk.proto;

public final class FilecoinProtos {
  private FilecoinProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ContextCfgFILOrBuilder extends
      // @@protoc_insertion_point(interface_extends:JUB.Proto.Filecoin.ContextCfgFIL)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string main_path = 1;</code>
     */
    String getMainPath();
    /**
     * <code>string main_path = 1;</code>
     */
    com.google.protobuf.ByteString
        getMainPathBytes();
  }
  /**
   * Protobuf type {@code JUB.Proto.Filecoin.ContextCfgFIL}
   */
  public  static final class ContextCfgFIL extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:JUB.Proto.Filecoin.ContextCfgFIL)
      ContextCfgFILOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ContextCfgFIL.newBuilder() to construct.
    private ContextCfgFIL(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ContextCfgFIL() {
      mainPath_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ContextCfgFIL();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ContextCfgFIL(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              mainPath_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FilecoinProtos.internal_static_JUB_Proto_Filecoin_ContextCfgFIL_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FilecoinProtos.internal_static_JUB_Proto_Filecoin_ContextCfgFIL_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ContextCfgFIL.class, Builder.class);
    }

    public static final int MAIN_PATH_FIELD_NUMBER = 1;
    private volatile Object mainPath_;
    /**
     * <code>string main_path = 1;</code>
     */
    public String getMainPath() {
      Object ref = mainPath_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        mainPath_ = s;
        return s;
      }
    }
    /**
     * <code>string main_path = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMainPathBytes() {
      Object ref = mainPath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        mainPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMainPathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mainPath_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMainPathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mainPath_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ContextCfgFIL)) {
        return super.equals(obj);
      }
      ContextCfgFIL other = (ContextCfgFIL) obj;

      if (!getMainPath()
          .equals(other.getMainPath())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MAIN_PATH_FIELD_NUMBER;
      hash = (53 * hash) + getMainPath().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ContextCfgFIL parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ContextCfgFIL parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ContextCfgFIL parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ContextCfgFIL parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ContextCfgFIL parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ContextCfgFIL parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ContextCfgFIL parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ContextCfgFIL parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ContextCfgFIL parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ContextCfgFIL parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ContextCfgFIL parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ContextCfgFIL parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ContextCfgFIL prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code JUB.Proto.Filecoin.ContextCfgFIL}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:JUB.Proto.Filecoin.ContextCfgFIL)
        ContextCfgFILOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FilecoinProtos.internal_static_JUB_Proto_Filecoin_ContextCfgFIL_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FilecoinProtos.internal_static_JUB_Proto_Filecoin_ContextCfgFIL_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ContextCfgFIL.class, Builder.class);
      }

      // Construct using com.jubiter.sdk.proto.FilecoinProtos.ContextCfgFIL.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        mainPath_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FilecoinProtos.internal_static_JUB_Proto_Filecoin_ContextCfgFIL_descriptor;
      }

      @Override
      public ContextCfgFIL getDefaultInstanceForType() {
        return ContextCfgFIL.getDefaultInstance();
      }

      @Override
      public ContextCfgFIL build() {
        ContextCfgFIL result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ContextCfgFIL buildPartial() {
        ContextCfgFIL result = new ContextCfgFIL(this);
        result.mainPath_ = mainPath_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ContextCfgFIL) {
          return mergeFrom((ContextCfgFIL)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ContextCfgFIL other) {
        if (other == ContextCfgFIL.getDefaultInstance()) return this;
        if (!other.getMainPath().isEmpty()) {
          mainPath_ = other.mainPath_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ContextCfgFIL parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ContextCfgFIL) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object mainPath_ = "";
      /**
       * <code>string main_path = 1;</code>
       */
      public String getMainPath() {
        Object ref = mainPath_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          mainPath_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string main_path = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMainPathBytes() {
        Object ref = mainPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          mainPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string main_path = 1;</code>
       */
      public Builder setMainPath(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mainPath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string main_path = 1;</code>
       */
      public Builder clearMainPath() {
        
        mainPath_ = getDefaultInstance().getMainPath();
        onChanged();
        return this;
      }
      /**
       * <code>string main_path = 1;</code>
       */
      public Builder setMainPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mainPath_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:JUB.Proto.Filecoin.ContextCfgFIL)
    }

    // @@protoc_insertion_point(class_scope:JUB.Proto.Filecoin.ContextCfgFIL)
    private static final ContextCfgFIL DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ContextCfgFIL();
    }

    public static ContextCfgFIL getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ContextCfgFIL>
        PARSER = new com.google.protobuf.AbstractParser<ContextCfgFIL>() {
      @Override
      public ContextCfgFIL parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ContextCfgFIL(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ContextCfgFIL> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ContextCfgFIL> getParserForType() {
      return PARSER;
    }

    @Override
    public ContextCfgFIL getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TransactionFILOrBuilder extends
      // @@protoc_insertion_point(interface_extends:JUB.Proto.Filecoin.TransactionFIL)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.JUB.Proto.Common.Bip44Path path = 1;</code>
     */
    boolean hasPath();
    /**
     * <code>.JUB.Proto.Common.Bip44Path path = 1;</code>
     */
    CommonProtos.Bip44Path getPath();
    /**
     * <code>.JUB.Proto.Common.Bip44Path path = 1;</code>
     */
    CommonProtos.Bip44PathOrBuilder getPathOrBuilder();

    /**
     * <code>uint32 nonce = 2;</code>
     */
    int getNonce();

    /**
     * <code>uint32 gas_limit = 3;</code>
     */
    int getGasLimit();

    /**
     * <code>string gas_fee_cap_in_atto = 4;</code>
     */
    String getGasFeeCapInAtto();
    /**
     * <code>string gas_fee_cap_in_atto = 4;</code>
     */
    com.google.protobuf.ByteString
        getGasFeeCapInAttoBytes();

    /**
     * <code>string gas_premium_in_atto = 5;</code>
     */
    String getGasPremiumInAtto();
    /**
     * <code>string gas_premium_in_atto = 5;</code>
     */
    com.google.protobuf.ByteString
        getGasPremiumInAttoBytes();

    /**
     * <code>string to = 6;</code>
     */
    String getTo();
    /**
     * <code>string to = 6;</code>
     */
    com.google.protobuf.ByteString
        getToBytes();

    /**
     * <code>string value_in_atto = 7;</code>
     */
    String getValueInAtto();
    /**
     * <code>string value_in_atto = 7;</code>
     */
    com.google.protobuf.ByteString
        getValueInAttoBytes();

    /**
     * <code>string input = 8;</code>
     */
    String getInput();
    /**
     * <code>string input = 8;</code>
     */
    com.google.protobuf.ByteString
        getInputBytes();
  }
  /**
   * Protobuf type {@code JUB.Proto.Filecoin.TransactionFIL}
   */
  public  static final class TransactionFIL extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:JUB.Proto.Filecoin.TransactionFIL)
      TransactionFILOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TransactionFIL.newBuilder() to construct.
    private TransactionFIL(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransactionFIL() {
      gasFeeCapInAtto_ = "";
      gasPremiumInAtto_ = "";
      to_ = "";
      valueInAtto_ = "";
      input_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new TransactionFIL();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TransactionFIL(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              CommonProtos.Bip44Path.Builder subBuilder = null;
              if (path_ != null) {
                subBuilder = path_.toBuilder();
              }
              path_ = input.readMessage(CommonProtos.Bip44Path.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(path_);
                path_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              nonce_ = input.readUInt32();
              break;
            }
            case 24: {

              gasLimit_ = input.readUInt32();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              gasFeeCapInAtto_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              gasPremiumInAtto_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              to_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              valueInAtto_ = s;
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              input_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FilecoinProtos.internal_static_JUB_Proto_Filecoin_TransactionFIL_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FilecoinProtos.internal_static_JUB_Proto_Filecoin_TransactionFIL_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TransactionFIL.class, Builder.class);
    }

    public static final int PATH_FIELD_NUMBER = 1;
    private CommonProtos.Bip44Path path_;
    /**
     * <code>.JUB.Proto.Common.Bip44Path path = 1;</code>
     */
    public boolean hasPath() {
      return path_ != null;
    }
    /**
     * <code>.JUB.Proto.Common.Bip44Path path = 1;</code>
     */
    public CommonProtos.Bip44Path getPath() {
      return path_ == null ? CommonProtos.Bip44Path.getDefaultInstance() : path_;
    }
    /**
     * <code>.JUB.Proto.Common.Bip44Path path = 1;</code>
     */
    public CommonProtos.Bip44PathOrBuilder getPathOrBuilder() {
      return getPath();
    }

    public static final int NONCE_FIELD_NUMBER = 2;
    private int nonce_;
    /**
     * <code>uint32 nonce = 2;</code>
     */
    public int getNonce() {
      return nonce_;
    }

    public static final int GAS_LIMIT_FIELD_NUMBER = 3;
    private int gasLimit_;
    /**
     * <code>uint32 gas_limit = 3;</code>
     */
    public int getGasLimit() {
      return gasLimit_;
    }

    public static final int GAS_FEE_CAP_IN_ATTO_FIELD_NUMBER = 4;
    private volatile Object gasFeeCapInAtto_;
    /**
     * <code>string gas_fee_cap_in_atto = 4;</code>
     */
    public String getGasFeeCapInAtto() {
      Object ref = gasFeeCapInAtto_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        gasFeeCapInAtto_ = s;
        return s;
      }
    }
    /**
     * <code>string gas_fee_cap_in_atto = 4;</code>
     */
    public com.google.protobuf.ByteString
        getGasFeeCapInAttoBytes() {
      Object ref = gasFeeCapInAtto_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        gasFeeCapInAtto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GAS_PREMIUM_IN_ATTO_FIELD_NUMBER = 5;
    private volatile Object gasPremiumInAtto_;
    /**
     * <code>string gas_premium_in_atto = 5;</code>
     */
    public String getGasPremiumInAtto() {
      Object ref = gasPremiumInAtto_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        gasPremiumInAtto_ = s;
        return s;
      }
    }
    /**
     * <code>string gas_premium_in_atto = 5;</code>
     */
    public com.google.protobuf.ByteString
        getGasPremiumInAttoBytes() {
      Object ref = gasPremiumInAtto_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        gasPremiumInAtto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TO_FIELD_NUMBER = 6;
    private volatile Object to_;
    /**
     * <code>string to = 6;</code>
     */
    public String getTo() {
      Object ref = to_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        to_ = s;
        return s;
      }
    }
    /**
     * <code>string to = 6;</code>
     */
    public com.google.protobuf.ByteString
        getToBytes() {
      Object ref = to_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_IN_ATTO_FIELD_NUMBER = 7;
    private volatile Object valueInAtto_;
    /**
     * <code>string value_in_atto = 7;</code>
     */
    public String getValueInAtto() {
      Object ref = valueInAtto_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        valueInAtto_ = s;
        return s;
      }
    }
    /**
     * <code>string value_in_atto = 7;</code>
     */
    public com.google.protobuf.ByteString
        getValueInAttoBytes() {
      Object ref = valueInAtto_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        valueInAtto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INPUT_FIELD_NUMBER = 8;
    private volatile Object input_;
    /**
     * <code>string input = 8;</code>
     */
    public String getInput() {
      Object ref = input_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        input_ = s;
        return s;
      }
    }
    /**
     * <code>string input = 8;</code>
     */
    public com.google.protobuf.ByteString
        getInputBytes() {
      Object ref = input_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        input_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (path_ != null) {
        output.writeMessage(1, getPath());
      }
      if (nonce_ != 0) {
        output.writeUInt32(2, nonce_);
      }
      if (gasLimit_ != 0) {
        output.writeUInt32(3, gasLimit_);
      }
      if (!getGasFeeCapInAttoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, gasFeeCapInAtto_);
      }
      if (!getGasPremiumInAttoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, gasPremiumInAtto_);
      }
      if (!getToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, to_);
      }
      if (!getValueInAttoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, valueInAtto_);
      }
      if (!getInputBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, input_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (path_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPath());
      }
      if (nonce_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, nonce_);
      }
      if (gasLimit_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, gasLimit_);
      }
      if (!getGasFeeCapInAttoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, gasFeeCapInAtto_);
      }
      if (!getGasPremiumInAttoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, gasPremiumInAtto_);
      }
      if (!getToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, to_);
      }
      if (!getValueInAttoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, valueInAtto_);
      }
      if (!getInputBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, input_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TransactionFIL)) {
        return super.equals(obj);
      }
      TransactionFIL other = (TransactionFIL) obj;

      if (hasPath() != other.hasPath()) return false;
      if (hasPath()) {
        if (!getPath()
            .equals(other.getPath())) return false;
      }
      if (getNonce()
          != other.getNonce()) return false;
      if (getGasLimit()
          != other.getGasLimit()) return false;
      if (!getGasFeeCapInAtto()
          .equals(other.getGasFeeCapInAtto())) return false;
      if (!getGasPremiumInAtto()
          .equals(other.getGasPremiumInAtto())) return false;
      if (!getTo()
          .equals(other.getTo())) return false;
      if (!getValueInAtto()
          .equals(other.getValueInAtto())) return false;
      if (!getInput()
          .equals(other.getInput())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPath()) {
        hash = (37 * hash) + PATH_FIELD_NUMBER;
        hash = (53 * hash) + getPath().hashCode();
      }
      hash = (37 * hash) + NONCE_FIELD_NUMBER;
      hash = (53 * hash) + getNonce();
      hash = (37 * hash) + GAS_LIMIT_FIELD_NUMBER;
      hash = (53 * hash) + getGasLimit();
      hash = (37 * hash) + GAS_FEE_CAP_IN_ATTO_FIELD_NUMBER;
      hash = (53 * hash) + getGasFeeCapInAtto().hashCode();
      hash = (37 * hash) + GAS_PREMIUM_IN_ATTO_FIELD_NUMBER;
      hash = (53 * hash) + getGasPremiumInAtto().hashCode();
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getTo().hashCode();
      hash = (37 * hash) + VALUE_IN_ATTO_FIELD_NUMBER;
      hash = (53 * hash) + getValueInAtto().hashCode();
      hash = (37 * hash) + INPUT_FIELD_NUMBER;
      hash = (53 * hash) + getInput().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TransactionFIL parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransactionFIL parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransactionFIL parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransactionFIL parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransactionFIL parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransactionFIL parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransactionFIL parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TransactionFIL parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TransactionFIL parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TransactionFIL parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TransactionFIL parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TransactionFIL parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TransactionFIL prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code JUB.Proto.Filecoin.TransactionFIL}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:JUB.Proto.Filecoin.TransactionFIL)
        TransactionFILOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FilecoinProtos.internal_static_JUB_Proto_Filecoin_TransactionFIL_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FilecoinProtos.internal_static_JUB_Proto_Filecoin_TransactionFIL_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TransactionFIL.class, Builder.class);
      }

      // Construct using com.jubiter.sdk.proto.FilecoinProtos.TransactionFIL.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (pathBuilder_ == null) {
          path_ = null;
        } else {
          path_ = null;
          pathBuilder_ = null;
        }
        nonce_ = 0;

        gasLimit_ = 0;

        gasFeeCapInAtto_ = "";

        gasPremiumInAtto_ = "";

        to_ = "";

        valueInAtto_ = "";

        input_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FilecoinProtos.internal_static_JUB_Proto_Filecoin_TransactionFIL_descriptor;
      }

      @Override
      public TransactionFIL getDefaultInstanceForType() {
        return TransactionFIL.getDefaultInstance();
      }

      @Override
      public TransactionFIL build() {
        TransactionFIL result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public TransactionFIL buildPartial() {
        TransactionFIL result = new TransactionFIL(this);
        if (pathBuilder_ == null) {
          result.path_ = path_;
        } else {
          result.path_ = pathBuilder_.build();
        }
        result.nonce_ = nonce_;
        result.gasLimit_ = gasLimit_;
        result.gasFeeCapInAtto_ = gasFeeCapInAtto_;
        result.gasPremiumInAtto_ = gasPremiumInAtto_;
        result.to_ = to_;
        result.valueInAtto_ = valueInAtto_;
        result.input_ = input_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TransactionFIL) {
          return mergeFrom((TransactionFIL)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TransactionFIL other) {
        if (other == TransactionFIL.getDefaultInstance()) return this;
        if (other.hasPath()) {
          mergePath(other.getPath());
        }
        if (other.getNonce() != 0) {
          setNonce(other.getNonce());
        }
        if (other.getGasLimit() != 0) {
          setGasLimit(other.getGasLimit());
        }
        if (!other.getGasFeeCapInAtto().isEmpty()) {
          gasFeeCapInAtto_ = other.gasFeeCapInAtto_;
          onChanged();
        }
        if (!other.getGasPremiumInAtto().isEmpty()) {
          gasPremiumInAtto_ = other.gasPremiumInAtto_;
          onChanged();
        }
        if (!other.getTo().isEmpty()) {
          to_ = other.to_;
          onChanged();
        }
        if (!other.getValueInAtto().isEmpty()) {
          valueInAtto_ = other.valueInAtto_;
          onChanged();
        }
        if (!other.getInput().isEmpty()) {
          input_ = other.input_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TransactionFIL parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TransactionFIL) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private CommonProtos.Bip44Path path_;
      private com.google.protobuf.SingleFieldBuilderV3<
          CommonProtos.Bip44Path, CommonProtos.Bip44Path.Builder, CommonProtos.Bip44PathOrBuilder> pathBuilder_;
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 1;</code>
       */
      public boolean hasPath() {
        return pathBuilder_ != null || path_ != null;
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 1;</code>
       */
      public CommonProtos.Bip44Path getPath() {
        if (pathBuilder_ == null) {
          return path_ == null ? CommonProtos.Bip44Path.getDefaultInstance() : path_;
        } else {
          return pathBuilder_.getMessage();
        }
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 1;</code>
       */
      public Builder setPath(CommonProtos.Bip44Path value) {
        if (pathBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          path_ = value;
          onChanged();
        } else {
          pathBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 1;</code>
       */
      public Builder setPath(
          CommonProtos.Bip44Path.Builder builderForValue) {
        if (pathBuilder_ == null) {
          path_ = builderForValue.build();
          onChanged();
        } else {
          pathBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 1;</code>
       */
      public Builder mergePath(CommonProtos.Bip44Path value) {
        if (pathBuilder_ == null) {
          if (path_ != null) {
            path_ =
              CommonProtos.Bip44Path.newBuilder(path_).mergeFrom(value).buildPartial();
          } else {
            path_ = value;
          }
          onChanged();
        } else {
          pathBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 1;</code>
       */
      public Builder clearPath() {
        if (pathBuilder_ == null) {
          path_ = null;
          onChanged();
        } else {
          path_ = null;
          pathBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 1;</code>
       */
      public CommonProtos.Bip44Path.Builder getPathBuilder() {
        
        onChanged();
        return getPathFieldBuilder().getBuilder();
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 1;</code>
       */
      public CommonProtos.Bip44PathOrBuilder getPathOrBuilder() {
        if (pathBuilder_ != null) {
          return pathBuilder_.getMessageOrBuilder();
        } else {
          return path_ == null ?
              CommonProtos.Bip44Path.getDefaultInstance() : path_;
        }
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          CommonProtos.Bip44Path, CommonProtos.Bip44Path.Builder, CommonProtos.Bip44PathOrBuilder>
          getPathFieldBuilder() {
        if (pathBuilder_ == null) {
          pathBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              CommonProtos.Bip44Path, CommonProtos.Bip44Path.Builder, CommonProtos.Bip44PathOrBuilder>(
                  getPath(),
                  getParentForChildren(),
                  isClean());
          path_ = null;
        }
        return pathBuilder_;
      }

      private int nonce_ ;
      /**
       * <code>uint32 nonce = 2;</code>
       */
      public int getNonce() {
        return nonce_;
      }
      /**
       * <code>uint32 nonce = 2;</code>
       */
      public Builder setNonce(int value) {
        
        nonce_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 nonce = 2;</code>
       */
      public Builder clearNonce() {
        
        nonce_ = 0;
        onChanged();
        return this;
      }

      private int gasLimit_ ;
      /**
       * <code>uint32 gas_limit = 3;</code>
       */
      public int getGasLimit() {
        return gasLimit_;
      }
      /**
       * <code>uint32 gas_limit = 3;</code>
       */
      public Builder setGasLimit(int value) {
        
        gasLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 gas_limit = 3;</code>
       */
      public Builder clearGasLimit() {
        
        gasLimit_ = 0;
        onChanged();
        return this;
      }

      private Object gasFeeCapInAtto_ = "";
      /**
       * <code>string gas_fee_cap_in_atto = 4;</code>
       */
      public String getGasFeeCapInAtto() {
        Object ref = gasFeeCapInAtto_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          gasFeeCapInAtto_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string gas_fee_cap_in_atto = 4;</code>
       */
      public com.google.protobuf.ByteString
          getGasFeeCapInAttoBytes() {
        Object ref = gasFeeCapInAtto_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          gasFeeCapInAtto_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string gas_fee_cap_in_atto = 4;</code>
       */
      public Builder setGasFeeCapInAtto(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gasFeeCapInAtto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string gas_fee_cap_in_atto = 4;</code>
       */
      public Builder clearGasFeeCapInAtto() {
        
        gasFeeCapInAtto_ = getDefaultInstance().getGasFeeCapInAtto();
        onChanged();
        return this;
      }
      /**
       * <code>string gas_fee_cap_in_atto = 4;</code>
       */
      public Builder setGasFeeCapInAttoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gasFeeCapInAtto_ = value;
        onChanged();
        return this;
      }

      private Object gasPremiumInAtto_ = "";
      /**
       * <code>string gas_premium_in_atto = 5;</code>
       */
      public String getGasPremiumInAtto() {
        Object ref = gasPremiumInAtto_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          gasPremiumInAtto_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string gas_premium_in_atto = 5;</code>
       */
      public com.google.protobuf.ByteString
          getGasPremiumInAttoBytes() {
        Object ref = gasPremiumInAtto_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          gasPremiumInAtto_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string gas_premium_in_atto = 5;</code>
       */
      public Builder setGasPremiumInAtto(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gasPremiumInAtto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string gas_premium_in_atto = 5;</code>
       */
      public Builder clearGasPremiumInAtto() {
        
        gasPremiumInAtto_ = getDefaultInstance().getGasPremiumInAtto();
        onChanged();
        return this;
      }
      /**
       * <code>string gas_premium_in_atto = 5;</code>
       */
      public Builder setGasPremiumInAttoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gasPremiumInAtto_ = value;
        onChanged();
        return this;
      }

      private Object to_ = "";
      /**
       * <code>string to = 6;</code>
       */
      public String getTo() {
        Object ref = to_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          to_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string to = 6;</code>
       */
      public com.google.protobuf.ByteString
          getToBytes() {
        Object ref = to_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          to_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string to = 6;</code>
       */
      public Builder setTo(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string to = 6;</code>
       */
      public Builder clearTo() {
        
        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }
      /**
       * <code>string to = 6;</code>
       */
      public Builder setToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        to_ = value;
        onChanged();
        return this;
      }

      private Object valueInAtto_ = "";
      /**
       * <code>string value_in_atto = 7;</code>
       */
      public String getValueInAtto() {
        Object ref = valueInAtto_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          valueInAtto_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string value_in_atto = 7;</code>
       */
      public com.google.protobuf.ByteString
          getValueInAttoBytes() {
        Object ref = valueInAtto_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          valueInAtto_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value_in_atto = 7;</code>
       */
      public Builder setValueInAtto(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        valueInAtto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string value_in_atto = 7;</code>
       */
      public Builder clearValueInAtto() {
        
        valueInAtto_ = getDefaultInstance().getValueInAtto();
        onChanged();
        return this;
      }
      /**
       * <code>string value_in_atto = 7;</code>
       */
      public Builder setValueInAttoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        valueInAtto_ = value;
        onChanged();
        return this;
      }

      private Object input_ = "";
      /**
       * <code>string input = 8;</code>
       */
      public String getInput() {
        Object ref = input_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          input_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string input = 8;</code>
       */
      public com.google.protobuf.ByteString
          getInputBytes() {
        Object ref = input_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          input_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string input = 8;</code>
       */
      public Builder setInput(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        input_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string input = 8;</code>
       */
      public Builder clearInput() {
        
        input_ = getDefaultInstance().getInput();
        onChanged();
        return this;
      }
      /**
       * <code>string input = 8;</code>
       */
      public Builder setInputBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        input_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:JUB.Proto.Filecoin.TransactionFIL)
    }

    // @@protoc_insertion_point(class_scope:JUB.Proto.Filecoin.TransactionFIL)
    private static final TransactionFIL DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TransactionFIL();
    }

    public static TransactionFIL getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TransactionFIL>
        PARSER = new com.google.protobuf.AbstractParser<TransactionFIL>() {
      @Override
      public TransactionFIL parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransactionFIL(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TransactionFIL> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TransactionFIL> getParserForType() {
      return PARSER;
    }

    @Override
    public TransactionFIL getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JUB_Proto_Filecoin_ContextCfgFIL_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JUB_Proto_Filecoin_ContextCfgFIL_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JUB_Proto_Filecoin_TransactionFIL_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JUB_Proto_Filecoin_TransactionFIL_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022Jub_Filecoin.proto\022\022JUB.Proto.Filecoin" +
      "\032\020Jub_Common.proto\"\"\n\rContextCfgFIL\022\021\n\tm" +
      "ain_path\030\001 \001(\t\"\311\001\n\016TransactionFIL\022)\n\004pat" +
      "h\030\001 \001(\0132\033.JUB.Proto.Common.Bip44Path\022\r\n\005" +
      "nonce\030\002 \001(\r\022\021\n\tgas_limit\030\003 \001(\r\022\033\n\023gas_fe" +
      "e_cap_in_atto\030\004 \001(\t\022\033\n\023gas_premium_in_at" +
      "to\030\005 \001(\t\022\n\n\002to\030\006 \001(\t\022\025\n\rvalue_in_atto\030\007 " +
      "\001(\t\022\r\n\005input\030\010 \001(\tB8\n\025com.jubiter.sdk.pr" +
      "otoB\016FilecoinProtos\242\002\016FilecoinProtosb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          CommonProtos.getDescriptor(),
        });
    internal_static_JUB_Proto_Filecoin_ContextCfgFIL_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_JUB_Proto_Filecoin_ContextCfgFIL_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JUB_Proto_Filecoin_ContextCfgFIL_descriptor,
        new String[] { "MainPath", });
    internal_static_JUB_Proto_Filecoin_TransactionFIL_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_JUB_Proto_Filecoin_TransactionFIL_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JUB_Proto_Filecoin_TransactionFIL_descriptor,
        new String[] { "Path", "Nonce", "GasLimit", "GasFeeCapInAtto", "GasPremiumInAtto", "To", "ValueInAtto", "Input", });
    CommonProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
