// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Jub_Hcash.proto

package com.jubiter.sdk.proto;

public final class HcashProtos {
  private HcashProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InputHCOrBuilder extends
      // @@protoc_insertion_point(interface_extends:JUB.Proto.Hcash.InputHC)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 amount = 1;</code>
     */
    long getAmount();

    /**
     * <code>.JUB.Proto.Common.Bip44Path path = 2;</code>
     */
    boolean hasPath();
    /**
     * <code>.JUB.Proto.Common.Bip44Path path = 2;</code>
     */
    CommonProtos.Bip44Path getPath();
    /**
     * <code>.JUB.Proto.Common.Bip44Path path = 2;</code>
     */
    CommonProtos.Bip44PathOrBuilder getPathOrBuilder();
  }
  /**
   * Protobuf type {@code JUB.Proto.Hcash.InputHC}
   */
  public  static final class InputHC extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:JUB.Proto.Hcash.InputHC)
      InputHCOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InputHC.newBuilder() to construct.
    private InputHC(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InputHC() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new InputHC();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InputHC(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              amount_ = input.readUInt64();
              break;
            }
            case 18: {
              CommonProtos.Bip44Path.Builder subBuilder = null;
              if (path_ != null) {
                subBuilder = path_.toBuilder();
              }
              path_ = input.readMessage(CommonProtos.Bip44Path.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(path_);
                path_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HcashProtos.internal_static_JUB_Proto_Hcash_InputHC_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HcashProtos.internal_static_JUB_Proto_Hcash_InputHC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              InputHC.class, Builder.class);
    }

    public static final int AMOUNT_FIELD_NUMBER = 1;
    private long amount_;
    /**
     * <code>uint64 amount = 1;</code>
     */
    public long getAmount() {
      return amount_;
    }

    public static final int PATH_FIELD_NUMBER = 2;
    private CommonProtos.Bip44Path path_;
    /**
     * <code>.JUB.Proto.Common.Bip44Path path = 2;</code>
     */
    public boolean hasPath() {
      return path_ != null;
    }
    /**
     * <code>.JUB.Proto.Common.Bip44Path path = 2;</code>
     */
    public CommonProtos.Bip44Path getPath() {
      return path_ == null ? CommonProtos.Bip44Path.getDefaultInstance() : path_;
    }
    /**
     * <code>.JUB.Proto.Common.Bip44Path path = 2;</code>
     */
    public CommonProtos.Bip44PathOrBuilder getPathOrBuilder() {
      return getPath();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (amount_ != 0L) {
        output.writeUInt64(1, amount_);
      }
      if (path_ != null) {
        output.writeMessage(2, getPath());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (amount_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, amount_);
      }
      if (path_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPath());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof InputHC)) {
        return super.equals(obj);
      }
      InputHC other = (InputHC) obj;

      if (getAmount()
          != other.getAmount()) return false;
      if (hasPath() != other.hasPath()) return false;
      if (hasPath()) {
        if (!getPath()
            .equals(other.getPath())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAmount());
      if (hasPath()) {
        hash = (37 * hash) + PATH_FIELD_NUMBER;
        hash = (53 * hash) + getPath().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static InputHC parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static InputHC parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static InputHC parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static InputHC parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static InputHC parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static InputHC parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static InputHC parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static InputHC parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static InputHC parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static InputHC parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static InputHC parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static InputHC parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(InputHC prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code JUB.Proto.Hcash.InputHC}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:JUB.Proto.Hcash.InputHC)
        InputHCOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HcashProtos.internal_static_JUB_Proto_Hcash_InputHC_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HcashProtos.internal_static_JUB_Proto_Hcash_InputHC_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                InputHC.class, Builder.class);
      }

      // Construct using com.jubiter.sdk.proto.HcashProtos.InputHC.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        amount_ = 0L;

        if (pathBuilder_ == null) {
          path_ = null;
        } else {
          path_ = null;
          pathBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HcashProtos.internal_static_JUB_Proto_Hcash_InputHC_descriptor;
      }

      @Override
      public InputHC getDefaultInstanceForType() {
        return InputHC.getDefaultInstance();
      }

      @Override
      public InputHC build() {
        InputHC result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public InputHC buildPartial() {
        InputHC result = new InputHC(this);
        result.amount_ = amount_;
        if (pathBuilder_ == null) {
          result.path_ = path_;
        } else {
          result.path_ = pathBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof InputHC) {
          return mergeFrom((InputHC)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(InputHC other) {
        if (other == InputHC.getDefaultInstance()) return this;
        if (other.getAmount() != 0L) {
          setAmount(other.getAmount());
        }
        if (other.hasPath()) {
          mergePath(other.getPath());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        InputHC parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (InputHC) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long amount_ ;
      /**
       * <code>uint64 amount = 1;</code>
       */
      public long getAmount() {
        return amount_;
      }
      /**
       * <code>uint64 amount = 1;</code>
       */
      public Builder setAmount(long value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 amount = 1;</code>
       */
      public Builder clearAmount() {
        
        amount_ = 0L;
        onChanged();
        return this;
      }

      private CommonProtos.Bip44Path path_;
      private com.google.protobuf.SingleFieldBuilderV3<
          CommonProtos.Bip44Path, CommonProtos.Bip44Path.Builder, CommonProtos.Bip44PathOrBuilder> pathBuilder_;
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 2;</code>
       */
      public boolean hasPath() {
        return pathBuilder_ != null || path_ != null;
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 2;</code>
       */
      public CommonProtos.Bip44Path getPath() {
        if (pathBuilder_ == null) {
          return path_ == null ? CommonProtos.Bip44Path.getDefaultInstance() : path_;
        } else {
          return pathBuilder_.getMessage();
        }
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 2;</code>
       */
      public Builder setPath(CommonProtos.Bip44Path value) {
        if (pathBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          path_ = value;
          onChanged();
        } else {
          pathBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 2;</code>
       */
      public Builder setPath(
          CommonProtos.Bip44Path.Builder builderForValue) {
        if (pathBuilder_ == null) {
          path_ = builderForValue.build();
          onChanged();
        } else {
          pathBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 2;</code>
       */
      public Builder mergePath(CommonProtos.Bip44Path value) {
        if (pathBuilder_ == null) {
          if (path_ != null) {
            path_ =
              CommonProtos.Bip44Path.newBuilder(path_).mergeFrom(value).buildPartial();
          } else {
            path_ = value;
          }
          onChanged();
        } else {
          pathBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 2;</code>
       */
      public Builder clearPath() {
        if (pathBuilder_ == null) {
          path_ = null;
          onChanged();
        } else {
          path_ = null;
          pathBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 2;</code>
       */
      public CommonProtos.Bip44Path.Builder getPathBuilder() {
        
        onChanged();
        return getPathFieldBuilder().getBuilder();
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 2;</code>
       */
      public CommonProtos.Bip44PathOrBuilder getPathOrBuilder() {
        if (pathBuilder_ != null) {
          return pathBuilder_.getMessageOrBuilder();
        } else {
          return path_ == null ?
              CommonProtos.Bip44Path.getDefaultInstance() : path_;
        }
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          CommonProtos.Bip44Path, CommonProtos.Bip44Path.Builder, CommonProtos.Bip44PathOrBuilder>
          getPathFieldBuilder() {
        if (pathBuilder_ == null) {
          pathBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              CommonProtos.Bip44Path, CommonProtos.Bip44Path.Builder, CommonProtos.Bip44PathOrBuilder>(
                  getPath(),
                  getParentForChildren(),
                  isClean());
          path_ = null;
        }
        return pathBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:JUB.Proto.Hcash.InputHC)
    }

    // @@protoc_insertion_point(class_scope:JUB.Proto.Hcash.InputHC)
    private static final InputHC DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new InputHC();
    }

    public static InputHC getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InputHC>
        PARSER = new com.google.protobuf.AbstractParser<InputHC>() {
      @Override
      public InputHC parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InputHC(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InputHC> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<InputHC> getParserForType() {
      return PARSER;
    }

    @Override
    public InputHC getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OutputHCOrBuilder extends
      // @@protoc_insertion_point(interface_extends:JUB.Proto.Hcash.OutputHC)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool change_address = 1;</code>
     */
    boolean getChangeAddress();

    /**
     * <code>.JUB.Proto.Common.Bip44Path path = 2;</code>
     */
    boolean hasPath();
    /**
     * <code>.JUB.Proto.Common.Bip44Path path = 2;</code>
     */
    CommonProtos.Bip44Path getPath();
    /**
     * <code>.JUB.Proto.Common.Bip44Path path = 2;</code>
     */
    CommonProtos.Bip44PathOrBuilder getPathOrBuilder();
  }
  /**
   * Protobuf type {@code JUB.Proto.Hcash.OutputHC}
   */
  public  static final class OutputHC extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:JUB.Proto.Hcash.OutputHC)
      OutputHCOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OutputHC.newBuilder() to construct.
    private OutputHC(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OutputHC() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new OutputHC();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OutputHC(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              changeAddress_ = input.readBool();
              break;
            }
            case 18: {
              CommonProtos.Bip44Path.Builder subBuilder = null;
              if (path_ != null) {
                subBuilder = path_.toBuilder();
              }
              path_ = input.readMessage(CommonProtos.Bip44Path.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(path_);
                path_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HcashProtos.internal_static_JUB_Proto_Hcash_OutputHC_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HcashProtos.internal_static_JUB_Proto_Hcash_OutputHC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OutputHC.class, Builder.class);
    }

    public static final int CHANGE_ADDRESS_FIELD_NUMBER = 1;
    private boolean changeAddress_;
    /**
     * <code>bool change_address = 1;</code>
     */
    public boolean getChangeAddress() {
      return changeAddress_;
    }

    public static final int PATH_FIELD_NUMBER = 2;
    private CommonProtos.Bip44Path path_;
    /**
     * <code>.JUB.Proto.Common.Bip44Path path = 2;</code>
     */
    public boolean hasPath() {
      return path_ != null;
    }
    /**
     * <code>.JUB.Proto.Common.Bip44Path path = 2;</code>
     */
    public CommonProtos.Bip44Path getPath() {
      return path_ == null ? CommonProtos.Bip44Path.getDefaultInstance() : path_;
    }
    /**
     * <code>.JUB.Proto.Common.Bip44Path path = 2;</code>
     */
    public CommonProtos.Bip44PathOrBuilder getPathOrBuilder() {
      return getPath();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (changeAddress_ != false) {
        output.writeBool(1, changeAddress_);
      }
      if (path_ != null) {
        output.writeMessage(2, getPath());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (changeAddress_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, changeAddress_);
      }
      if (path_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPath());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof OutputHC)) {
        return super.equals(obj);
      }
      OutputHC other = (OutputHC) obj;

      if (getChangeAddress()
          != other.getChangeAddress()) return false;
      if (hasPath() != other.hasPath()) return false;
      if (hasPath()) {
        if (!getPath()
            .equals(other.getPath())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CHANGE_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getChangeAddress());
      if (hasPath()) {
        hash = (37 * hash) + PATH_FIELD_NUMBER;
        hash = (53 * hash) + getPath().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static OutputHC parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OutputHC parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OutputHC parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OutputHC parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OutputHC parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OutputHC parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OutputHC parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OutputHC parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static OutputHC parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static OutputHC parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static OutputHC parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OutputHC parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(OutputHC prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code JUB.Proto.Hcash.OutputHC}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:JUB.Proto.Hcash.OutputHC)
        OutputHCOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HcashProtos.internal_static_JUB_Proto_Hcash_OutputHC_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HcashProtos.internal_static_JUB_Proto_Hcash_OutputHC_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OutputHC.class, Builder.class);
      }

      // Construct using com.jubiter.sdk.proto.HcashProtos.OutputHC.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        changeAddress_ = false;

        if (pathBuilder_ == null) {
          path_ = null;
        } else {
          path_ = null;
          pathBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HcashProtos.internal_static_JUB_Proto_Hcash_OutputHC_descriptor;
      }

      @Override
      public OutputHC getDefaultInstanceForType() {
        return OutputHC.getDefaultInstance();
      }

      @Override
      public OutputHC build() {
        OutputHC result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public OutputHC buildPartial() {
        OutputHC result = new OutputHC(this);
        result.changeAddress_ = changeAddress_;
        if (pathBuilder_ == null) {
          result.path_ = path_;
        } else {
          result.path_ = pathBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OutputHC) {
          return mergeFrom((OutputHC)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OutputHC other) {
        if (other == OutputHC.getDefaultInstance()) return this;
        if (other.getChangeAddress() != false) {
          setChangeAddress(other.getChangeAddress());
        }
        if (other.hasPath()) {
          mergePath(other.getPath());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        OutputHC parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (OutputHC) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean changeAddress_ ;
      /**
       * <code>bool change_address = 1;</code>
       */
      public boolean getChangeAddress() {
        return changeAddress_;
      }
      /**
       * <code>bool change_address = 1;</code>
       */
      public Builder setChangeAddress(boolean value) {
        
        changeAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool change_address = 1;</code>
       */
      public Builder clearChangeAddress() {
        
        changeAddress_ = false;
        onChanged();
        return this;
      }

      private CommonProtos.Bip44Path path_;
      private com.google.protobuf.SingleFieldBuilderV3<
          CommonProtos.Bip44Path, CommonProtos.Bip44Path.Builder, CommonProtos.Bip44PathOrBuilder> pathBuilder_;
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 2;</code>
       */
      public boolean hasPath() {
        return pathBuilder_ != null || path_ != null;
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 2;</code>
       */
      public CommonProtos.Bip44Path getPath() {
        if (pathBuilder_ == null) {
          return path_ == null ? CommonProtos.Bip44Path.getDefaultInstance() : path_;
        } else {
          return pathBuilder_.getMessage();
        }
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 2;</code>
       */
      public Builder setPath(CommonProtos.Bip44Path value) {
        if (pathBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          path_ = value;
          onChanged();
        } else {
          pathBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 2;</code>
       */
      public Builder setPath(
          CommonProtos.Bip44Path.Builder builderForValue) {
        if (pathBuilder_ == null) {
          path_ = builderForValue.build();
          onChanged();
        } else {
          pathBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 2;</code>
       */
      public Builder mergePath(CommonProtos.Bip44Path value) {
        if (pathBuilder_ == null) {
          if (path_ != null) {
            path_ =
              CommonProtos.Bip44Path.newBuilder(path_).mergeFrom(value).buildPartial();
          } else {
            path_ = value;
          }
          onChanged();
        } else {
          pathBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 2;</code>
       */
      public Builder clearPath() {
        if (pathBuilder_ == null) {
          path_ = null;
          onChanged();
        } else {
          path_ = null;
          pathBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 2;</code>
       */
      public CommonProtos.Bip44Path.Builder getPathBuilder() {
        
        onChanged();
        return getPathFieldBuilder().getBuilder();
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 2;</code>
       */
      public CommonProtos.Bip44PathOrBuilder getPathOrBuilder() {
        if (pathBuilder_ != null) {
          return pathBuilder_.getMessageOrBuilder();
        } else {
          return path_ == null ?
              CommonProtos.Bip44Path.getDefaultInstance() : path_;
        }
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          CommonProtos.Bip44Path, CommonProtos.Bip44Path.Builder, CommonProtos.Bip44PathOrBuilder>
          getPathFieldBuilder() {
        if (pathBuilder_ == null) {
          pathBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              CommonProtos.Bip44Path, CommonProtos.Bip44Path.Builder, CommonProtos.Bip44PathOrBuilder>(
                  getPath(),
                  getParentForChildren(),
                  isClean());
          path_ = null;
        }
        return pathBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:JUB.Proto.Hcash.OutputHC)
    }

    // @@protoc_insertion_point(class_scope:JUB.Proto.Hcash.OutputHC)
    private static final OutputHC DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new OutputHC();
    }

    public static OutputHC getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OutputHC>
        PARSER = new com.google.protobuf.AbstractParser<OutputHC>() {
      @Override
      public OutputHC parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OutputHC(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OutputHC> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<OutputHC> getParserForType() {
      return PARSER;
    }

    @Override
    public OutputHC getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TransactionHCOrBuilder extends
      // @@protoc_insertion_point(interface_extends:JUB.Proto.Hcash.TransactionHC)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 version = 1;</code>
     */
    int getVersion();

    /**
     * <code>uint32 locktime = 2;</code>
     */
    int getLocktime();

    /**
     * <code>repeated .JUB.Proto.Hcash.InputHC inputs = 3;</code>
     */
    java.util.List<InputHC>
        getInputsList();
    /**
     * <code>repeated .JUB.Proto.Hcash.InputHC inputs = 3;</code>
     */
    InputHC getInputs(int index);
    /**
     * <code>repeated .JUB.Proto.Hcash.InputHC inputs = 3;</code>
     */
    int getInputsCount();
    /**
     * <code>repeated .JUB.Proto.Hcash.InputHC inputs = 3;</code>
     */
    java.util.List<? extends InputHCOrBuilder>
        getInputsOrBuilderList();
    /**
     * <code>repeated .JUB.Proto.Hcash.InputHC inputs = 3;</code>
     */
    InputHCOrBuilder getInputsOrBuilder(
            int index);

    /**
     * <code>repeated .JUB.Proto.Hcash.OutputHC outputs = 4;</code>
     */
    java.util.List<OutputHC>
        getOutputsList();
    /**
     * <code>repeated .JUB.Proto.Hcash.OutputHC outputs = 4;</code>
     */
    OutputHC getOutputs(int index);
    /**
     * <code>repeated .JUB.Proto.Hcash.OutputHC outputs = 4;</code>
     */
    int getOutputsCount();
    /**
     * <code>repeated .JUB.Proto.Hcash.OutputHC outputs = 4;</code>
     */
    java.util.List<? extends OutputHCOrBuilder>
        getOutputsOrBuilderList();
    /**
     * <code>repeated .JUB.Proto.Hcash.OutputHC outputs = 4;</code>
     */
    OutputHCOrBuilder getOutputsOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code JUB.Proto.Hcash.TransactionHC}
   */
  public  static final class TransactionHC extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:JUB.Proto.Hcash.TransactionHC)
      TransactionHCOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TransactionHC.newBuilder() to construct.
    private TransactionHC(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransactionHC() {
      inputs_ = java.util.Collections.emptyList();
      outputs_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new TransactionHC();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TransactionHC(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              version_ = input.readUInt32();
              break;
            }
            case 16: {

              locktime_ = input.readUInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                inputs_ = new java.util.ArrayList<InputHC>();
                mutable_bitField0_ |= 0x00000001;
              }
              inputs_.add(
                  input.readMessage(InputHC.parser(), extensionRegistry));
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                outputs_ = new java.util.ArrayList<OutputHC>();
                mutable_bitField0_ |= 0x00000002;
              }
              outputs_.add(
                  input.readMessage(OutputHC.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          inputs_ = java.util.Collections.unmodifiableList(inputs_);
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          outputs_ = java.util.Collections.unmodifiableList(outputs_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HcashProtos.internal_static_JUB_Proto_Hcash_TransactionHC_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HcashProtos.internal_static_JUB_Proto_Hcash_TransactionHC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TransactionHC.class, Builder.class);
    }

    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>uint32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int LOCKTIME_FIELD_NUMBER = 2;
    private int locktime_;
    /**
     * <code>uint32 locktime = 2;</code>
     */
    public int getLocktime() {
      return locktime_;
    }

    public static final int INPUTS_FIELD_NUMBER = 3;
    private java.util.List<InputHC> inputs_;
    /**
     * <code>repeated .JUB.Proto.Hcash.InputHC inputs = 3;</code>
     */
    public java.util.List<InputHC> getInputsList() {
      return inputs_;
    }
    /**
     * <code>repeated .JUB.Proto.Hcash.InputHC inputs = 3;</code>
     */
    public java.util.List<? extends InputHCOrBuilder>
        getInputsOrBuilderList() {
      return inputs_;
    }
    /**
     * <code>repeated .JUB.Proto.Hcash.InputHC inputs = 3;</code>
     */
    public int getInputsCount() {
      return inputs_.size();
    }
    /**
     * <code>repeated .JUB.Proto.Hcash.InputHC inputs = 3;</code>
     */
    public InputHC getInputs(int index) {
      return inputs_.get(index);
    }
    /**
     * <code>repeated .JUB.Proto.Hcash.InputHC inputs = 3;</code>
     */
    public InputHCOrBuilder getInputsOrBuilder(
        int index) {
      return inputs_.get(index);
    }

    public static final int OUTPUTS_FIELD_NUMBER = 4;
    private java.util.List<OutputHC> outputs_;
    /**
     * <code>repeated .JUB.Proto.Hcash.OutputHC outputs = 4;</code>
     */
    public java.util.List<OutputHC> getOutputsList() {
      return outputs_;
    }
    /**
     * <code>repeated .JUB.Proto.Hcash.OutputHC outputs = 4;</code>
     */
    public java.util.List<? extends OutputHCOrBuilder>
        getOutputsOrBuilderList() {
      return outputs_;
    }
    /**
     * <code>repeated .JUB.Proto.Hcash.OutputHC outputs = 4;</code>
     */
    public int getOutputsCount() {
      return outputs_.size();
    }
    /**
     * <code>repeated .JUB.Proto.Hcash.OutputHC outputs = 4;</code>
     */
    public OutputHC getOutputs(int index) {
      return outputs_.get(index);
    }
    /**
     * <code>repeated .JUB.Proto.Hcash.OutputHC outputs = 4;</code>
     */
    public OutputHCOrBuilder getOutputsOrBuilder(
        int index) {
      return outputs_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (version_ != 0) {
        output.writeUInt32(1, version_);
      }
      if (locktime_ != 0) {
        output.writeUInt32(2, locktime_);
      }
      for (int i = 0; i < inputs_.size(); i++) {
        output.writeMessage(3, inputs_.get(i));
      }
      for (int i = 0; i < outputs_.size(); i++) {
        output.writeMessage(4, outputs_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, version_);
      }
      if (locktime_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, locktime_);
      }
      for (int i = 0; i < inputs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, inputs_.get(i));
      }
      for (int i = 0; i < outputs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, outputs_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TransactionHC)) {
        return super.equals(obj);
      }
      TransactionHC other = (TransactionHC) obj;

      if (getVersion()
          != other.getVersion()) return false;
      if (getLocktime()
          != other.getLocktime()) return false;
      if (!getInputsList()
          .equals(other.getInputsList())) return false;
      if (!getOutputsList()
          .equals(other.getOutputsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + LOCKTIME_FIELD_NUMBER;
      hash = (53 * hash) + getLocktime();
      if (getInputsCount() > 0) {
        hash = (37 * hash) + INPUTS_FIELD_NUMBER;
        hash = (53 * hash) + getInputsList().hashCode();
      }
      if (getOutputsCount() > 0) {
        hash = (37 * hash) + OUTPUTS_FIELD_NUMBER;
        hash = (53 * hash) + getOutputsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TransactionHC parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransactionHC parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransactionHC parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransactionHC parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransactionHC parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransactionHC parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransactionHC parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TransactionHC parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TransactionHC parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TransactionHC parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TransactionHC parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TransactionHC parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TransactionHC prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code JUB.Proto.Hcash.TransactionHC}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:JUB.Proto.Hcash.TransactionHC)
        TransactionHCOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HcashProtos.internal_static_JUB_Proto_Hcash_TransactionHC_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HcashProtos.internal_static_JUB_Proto_Hcash_TransactionHC_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TransactionHC.class, Builder.class);
      }

      // Construct using com.jubiter.sdk.proto.HcashProtos.TransactionHC.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getInputsFieldBuilder();
          getOutputsFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        version_ = 0;

        locktime_ = 0;

        if (inputsBuilder_ == null) {
          inputs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          inputsBuilder_.clear();
        }
        if (outputsBuilder_ == null) {
          outputs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          outputsBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HcashProtos.internal_static_JUB_Proto_Hcash_TransactionHC_descriptor;
      }

      @Override
      public TransactionHC getDefaultInstanceForType() {
        return TransactionHC.getDefaultInstance();
      }

      @Override
      public TransactionHC build() {
        TransactionHC result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public TransactionHC buildPartial() {
        TransactionHC result = new TransactionHC(this);
        int from_bitField0_ = bitField0_;
        result.version_ = version_;
        result.locktime_ = locktime_;
        if (inputsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            inputs_ = java.util.Collections.unmodifiableList(inputs_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.inputs_ = inputs_;
        } else {
          result.inputs_ = inputsBuilder_.build();
        }
        if (outputsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            outputs_ = java.util.Collections.unmodifiableList(outputs_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.outputs_ = outputs_;
        } else {
          result.outputs_ = outputsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TransactionHC) {
          return mergeFrom((TransactionHC)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TransactionHC other) {
        if (other == TransactionHC.getDefaultInstance()) return this;
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (other.getLocktime() != 0) {
          setLocktime(other.getLocktime());
        }
        if (inputsBuilder_ == null) {
          if (!other.inputs_.isEmpty()) {
            if (inputs_.isEmpty()) {
              inputs_ = other.inputs_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureInputsIsMutable();
              inputs_.addAll(other.inputs_);
            }
            onChanged();
          }
        } else {
          if (!other.inputs_.isEmpty()) {
            if (inputsBuilder_.isEmpty()) {
              inputsBuilder_.dispose();
              inputsBuilder_ = null;
              inputs_ = other.inputs_;
              bitField0_ = (bitField0_ & ~0x00000001);
              inputsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getInputsFieldBuilder() : null;
            } else {
              inputsBuilder_.addAllMessages(other.inputs_);
            }
          }
        }
        if (outputsBuilder_ == null) {
          if (!other.outputs_.isEmpty()) {
            if (outputs_.isEmpty()) {
              outputs_ = other.outputs_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureOutputsIsMutable();
              outputs_.addAll(other.outputs_);
            }
            onChanged();
          }
        } else {
          if (!other.outputs_.isEmpty()) {
            if (outputsBuilder_.isEmpty()) {
              outputsBuilder_.dispose();
              outputsBuilder_ = null;
              outputs_ = other.outputs_;
              bitField0_ = (bitField0_ & ~0x00000002);
              outputsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getOutputsFieldBuilder() : null;
            } else {
              outputsBuilder_.addAllMessages(other.outputs_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TransactionHC parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TransactionHC) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int version_ ;
      /**
       * <code>uint32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>uint32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 version = 1;</code>
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private int locktime_ ;
      /**
       * <code>uint32 locktime = 2;</code>
       */
      public int getLocktime() {
        return locktime_;
      }
      /**
       * <code>uint32 locktime = 2;</code>
       */
      public Builder setLocktime(int value) {
        
        locktime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 locktime = 2;</code>
       */
      public Builder clearLocktime() {
        
        locktime_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<InputHC> inputs_ =
        java.util.Collections.emptyList();
      private void ensureInputsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          inputs_ = new java.util.ArrayList<InputHC>(inputs_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          InputHC, InputHC.Builder, InputHCOrBuilder> inputsBuilder_;

      /**
       * <code>repeated .JUB.Proto.Hcash.InputHC inputs = 3;</code>
       */
      public java.util.List<InputHC> getInputsList() {
        if (inputsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(inputs_);
        } else {
          return inputsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.InputHC inputs = 3;</code>
       */
      public int getInputsCount() {
        if (inputsBuilder_ == null) {
          return inputs_.size();
        } else {
          return inputsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.InputHC inputs = 3;</code>
       */
      public InputHC getInputs(int index) {
        if (inputsBuilder_ == null) {
          return inputs_.get(index);
        } else {
          return inputsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.InputHC inputs = 3;</code>
       */
      public Builder setInputs(
          int index, InputHC value) {
        if (inputsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInputsIsMutable();
          inputs_.set(index, value);
          onChanged();
        } else {
          inputsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.InputHC inputs = 3;</code>
       */
      public Builder setInputs(
          int index, InputHC.Builder builderForValue) {
        if (inputsBuilder_ == null) {
          ensureInputsIsMutable();
          inputs_.set(index, builderForValue.build());
          onChanged();
        } else {
          inputsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.InputHC inputs = 3;</code>
       */
      public Builder addInputs(InputHC value) {
        if (inputsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInputsIsMutable();
          inputs_.add(value);
          onChanged();
        } else {
          inputsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.InputHC inputs = 3;</code>
       */
      public Builder addInputs(
          int index, InputHC value) {
        if (inputsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInputsIsMutable();
          inputs_.add(index, value);
          onChanged();
        } else {
          inputsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.InputHC inputs = 3;</code>
       */
      public Builder addInputs(
          InputHC.Builder builderForValue) {
        if (inputsBuilder_ == null) {
          ensureInputsIsMutable();
          inputs_.add(builderForValue.build());
          onChanged();
        } else {
          inputsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.InputHC inputs = 3;</code>
       */
      public Builder addInputs(
          int index, InputHC.Builder builderForValue) {
        if (inputsBuilder_ == null) {
          ensureInputsIsMutable();
          inputs_.add(index, builderForValue.build());
          onChanged();
        } else {
          inputsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.InputHC inputs = 3;</code>
       */
      public Builder addAllInputs(
          Iterable<? extends InputHC> values) {
        if (inputsBuilder_ == null) {
          ensureInputsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, inputs_);
          onChanged();
        } else {
          inputsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.InputHC inputs = 3;</code>
       */
      public Builder clearInputs() {
        if (inputsBuilder_ == null) {
          inputs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          inputsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.InputHC inputs = 3;</code>
       */
      public Builder removeInputs(int index) {
        if (inputsBuilder_ == null) {
          ensureInputsIsMutable();
          inputs_.remove(index);
          onChanged();
        } else {
          inputsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.InputHC inputs = 3;</code>
       */
      public InputHC.Builder getInputsBuilder(
          int index) {
        return getInputsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.InputHC inputs = 3;</code>
       */
      public InputHCOrBuilder getInputsOrBuilder(
          int index) {
        if (inputsBuilder_ == null) {
          return inputs_.get(index);  } else {
          return inputsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.InputHC inputs = 3;</code>
       */
      public java.util.List<? extends InputHCOrBuilder>
           getInputsOrBuilderList() {
        if (inputsBuilder_ != null) {
          return inputsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(inputs_);
        }
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.InputHC inputs = 3;</code>
       */
      public InputHC.Builder addInputsBuilder() {
        return getInputsFieldBuilder().addBuilder(
            InputHC.getDefaultInstance());
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.InputHC inputs = 3;</code>
       */
      public InputHC.Builder addInputsBuilder(
          int index) {
        return getInputsFieldBuilder().addBuilder(
            index, InputHC.getDefaultInstance());
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.InputHC inputs = 3;</code>
       */
      public java.util.List<InputHC.Builder>
           getInputsBuilderList() {
        return getInputsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          InputHC, InputHC.Builder, InputHCOrBuilder>
          getInputsFieldBuilder() {
        if (inputsBuilder_ == null) {
          inputsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              InputHC, InputHC.Builder, InputHCOrBuilder>(
                  inputs_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          inputs_ = null;
        }
        return inputsBuilder_;
      }

      private java.util.List<OutputHC> outputs_ =
        java.util.Collections.emptyList();
      private void ensureOutputsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          outputs_ = new java.util.ArrayList<OutputHC>(outputs_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          OutputHC, OutputHC.Builder, OutputHCOrBuilder> outputsBuilder_;

      /**
       * <code>repeated .JUB.Proto.Hcash.OutputHC outputs = 4;</code>
       */
      public java.util.List<OutputHC> getOutputsList() {
        if (outputsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(outputs_);
        } else {
          return outputsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.OutputHC outputs = 4;</code>
       */
      public int getOutputsCount() {
        if (outputsBuilder_ == null) {
          return outputs_.size();
        } else {
          return outputsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.OutputHC outputs = 4;</code>
       */
      public OutputHC getOutputs(int index) {
        if (outputsBuilder_ == null) {
          return outputs_.get(index);
        } else {
          return outputsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.OutputHC outputs = 4;</code>
       */
      public Builder setOutputs(
          int index, OutputHC value) {
        if (outputsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOutputsIsMutable();
          outputs_.set(index, value);
          onChanged();
        } else {
          outputsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.OutputHC outputs = 4;</code>
       */
      public Builder setOutputs(
          int index, OutputHC.Builder builderForValue) {
        if (outputsBuilder_ == null) {
          ensureOutputsIsMutable();
          outputs_.set(index, builderForValue.build());
          onChanged();
        } else {
          outputsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.OutputHC outputs = 4;</code>
       */
      public Builder addOutputs(OutputHC value) {
        if (outputsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOutputsIsMutable();
          outputs_.add(value);
          onChanged();
        } else {
          outputsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.OutputHC outputs = 4;</code>
       */
      public Builder addOutputs(
          int index, OutputHC value) {
        if (outputsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOutputsIsMutable();
          outputs_.add(index, value);
          onChanged();
        } else {
          outputsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.OutputHC outputs = 4;</code>
       */
      public Builder addOutputs(
          OutputHC.Builder builderForValue) {
        if (outputsBuilder_ == null) {
          ensureOutputsIsMutable();
          outputs_.add(builderForValue.build());
          onChanged();
        } else {
          outputsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.OutputHC outputs = 4;</code>
       */
      public Builder addOutputs(
          int index, OutputHC.Builder builderForValue) {
        if (outputsBuilder_ == null) {
          ensureOutputsIsMutable();
          outputs_.add(index, builderForValue.build());
          onChanged();
        } else {
          outputsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.OutputHC outputs = 4;</code>
       */
      public Builder addAllOutputs(
          Iterable<? extends OutputHC> values) {
        if (outputsBuilder_ == null) {
          ensureOutputsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, outputs_);
          onChanged();
        } else {
          outputsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.OutputHC outputs = 4;</code>
       */
      public Builder clearOutputs() {
        if (outputsBuilder_ == null) {
          outputs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          outputsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.OutputHC outputs = 4;</code>
       */
      public Builder removeOutputs(int index) {
        if (outputsBuilder_ == null) {
          ensureOutputsIsMutable();
          outputs_.remove(index);
          onChanged();
        } else {
          outputsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.OutputHC outputs = 4;</code>
       */
      public OutputHC.Builder getOutputsBuilder(
          int index) {
        return getOutputsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.OutputHC outputs = 4;</code>
       */
      public OutputHCOrBuilder getOutputsOrBuilder(
          int index) {
        if (outputsBuilder_ == null) {
          return outputs_.get(index);  } else {
          return outputsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.OutputHC outputs = 4;</code>
       */
      public java.util.List<? extends OutputHCOrBuilder>
           getOutputsOrBuilderList() {
        if (outputsBuilder_ != null) {
          return outputsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(outputs_);
        }
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.OutputHC outputs = 4;</code>
       */
      public OutputHC.Builder addOutputsBuilder() {
        return getOutputsFieldBuilder().addBuilder(
            OutputHC.getDefaultInstance());
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.OutputHC outputs = 4;</code>
       */
      public OutputHC.Builder addOutputsBuilder(
          int index) {
        return getOutputsFieldBuilder().addBuilder(
            index, OutputHC.getDefaultInstance());
      }
      /**
       * <code>repeated .JUB.Proto.Hcash.OutputHC outputs = 4;</code>
       */
      public java.util.List<OutputHC.Builder>
           getOutputsBuilderList() {
        return getOutputsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          OutputHC, OutputHC.Builder, OutputHCOrBuilder>
          getOutputsFieldBuilder() {
        if (outputsBuilder_ == null) {
          outputsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              OutputHC, OutputHC.Builder, OutputHCOrBuilder>(
                  outputs_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          outputs_ = null;
        }
        return outputsBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:JUB.Proto.Hcash.TransactionHC)
    }

    // @@protoc_insertion_point(class_scope:JUB.Proto.Hcash.TransactionHC)
    private static final TransactionHC DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TransactionHC();
    }

    public static TransactionHC getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TransactionHC>
        PARSER = new com.google.protobuf.AbstractParser<TransactionHC>() {
      @Override
      public TransactionHC parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransactionHC(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TransactionHC> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TransactionHC> getParserForType() {
      return PARSER;
    }

    @Override
    public TransactionHC getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JUB_Proto_Hcash_InputHC_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JUB_Proto_Hcash_InputHC_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JUB_Proto_Hcash_OutputHC_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JUB_Proto_Hcash_OutputHC_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JUB_Proto_Hcash_TransactionHC_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JUB_Proto_Hcash_TransactionHC_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017Jub_Hcash.proto\022\017JUB.Proto.Hcash\032\020Jub_" +
      "Common.proto\"D\n\007InputHC\022\016\n\006amount\030\001 \001(\004\022" +
      ")\n\004path\030\002 \001(\0132\033.JUB.Proto.Common.Bip44Pa" +
      "th\"M\n\010OutputHC\022\026\n\016change_address\030\001 \001(\010\022)" +
      "\n\004path\030\002 \001(\0132\033.JUB.Proto.Common.Bip44Pat" +
      "h\"\210\001\n\rTransactionHC\022\017\n\007version\030\001 \001(\r\022\020\n\010" +
      "locktime\030\002 \001(\r\022(\n\006inputs\030\003 \003(\0132\030.JUB.Pro" +
      "to.Hcash.InputHC\022*\n\007outputs\030\004 \003(\0132\031.JUB." +
      "Proto.Hcash.OutputHCB2\n\025com.jubiter.sdk." +
      "protoB\013HcashProtos\242\002\013HcashProtosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          CommonProtos.getDescriptor(),
        });
    internal_static_JUB_Proto_Hcash_InputHC_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_JUB_Proto_Hcash_InputHC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JUB_Proto_Hcash_InputHC_descriptor,
        new String[] { "Amount", "Path", });
    internal_static_JUB_Proto_Hcash_OutputHC_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_JUB_Proto_Hcash_OutputHC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JUB_Proto_Hcash_OutputHC_descriptor,
        new String[] { "ChangeAddress", "Path", });
    internal_static_JUB_Proto_Hcash_TransactionHC_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_JUB_Proto_Hcash_TransactionHC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JUB_Proto_Hcash_TransactionHC_descriptor,
        new String[] { "Version", "Locktime", "Inputs", "Outputs", });
    CommonProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
