# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ '2.4' ]
    # 语义化版本号限制
    # https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # 检测语义化版本号
#  verify_tag:
#    runs-on: ubuntu-latest
#    if: startsWith(github.ref, 'refs/tags/')
#    outputs:
#      # 对外返回值，true: 正则匹配符合，false: 不符合
#      match_value: ${{ steps.regex-match.outputs.match != '' }}
#    steps:
#      - name: Get tag
#        id: tag
#        uses: dawidd6/action-get-tag@v1.0.0
#
#      - uses: actions-ecosystem/action-regex-match@v2
#        id: regex-match
#        with:
#          text: ${{ steps.tag.outputs.tag }}
#          regex: '^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$'

  # This workflow contains a single job called "build"
  build:
#    needs: [verify_tag]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # 检测 tag 验证结果
#    if: ${{ needs.verify_tag.outputs.match_value }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v1

    - name: submodule
      run: git submodule update --init --recursive
              
    - name: permission
      run: |
        sudo chmod 777 ./gradlew
        sudo chmod 777 ./ActionBuild.sh
        
    - name: Setup NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r21e
        add-to-path: false
        
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.10.2'
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        body_path: ./release_logs/${{github.ref}}.md

    # 构建 apk
    - name: Build apk
      run: |
            ./gradlew assembleDebug
            ./gradlew assembleRelease
    # 上传 app 文件
    - name: Upload APK
      uses: softprops/action-gh-release@v1
      with:
        files: ./app/build/outputs/apk/release/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # 上传 app 文件
    - name: Upload AAR
      uses: softprops/action-gh-release@v1
      with:
        files: ./sdk/build/outputs/aar/*.aar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
