# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v1
      with:
         submodules: true
              
    - name: permission
      run: |
        sudo chmod 777 ./gradlew
        sudo chmod 777 ./ActionBuild.sh
        
    - name: Android Build env
      uses: vgaidarji/android-github-actions-build@v1.0.1
      with: 
         args: "./ActionBuild.sh"

    - name: Zip Build
      run: |
        zip -u JubSDK-Android.zip ./sdk/build/outputs/aar/sdk-release.aar 
        zip -u JubSDK-Android.zip ./app/build/outputs/apk/release/app-release-unsigned.apk 
